version: "3"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile.${NODE_ENV:-development}
    container_name: kronos-server
    image: kronos-server-${NODE_ENV:-development}
    links:
      - database
    ports:
      - "5000:5000"
    volumes:
      - ./server/app:/home/node

  database:
    build: database
    container_name: kronos-database
    image: kronos-database
    ports:
      - "8080:8080"
    volumes:
      - ./database/data:/data
