version: "3"

services:
  node:
    build: ./node
    links:
      - rethinkdb
    ports:
      - "5000:5000"
    user: "node"
    volumes:
      - ./node/app/index.js:/home/node/index.js

  rethinkdb:
    build: ./rethinkdb
    ports:
      - "8080:8080"
    volumes:
      - ./rethinkdb/data:/data
